### PR TITLE
checkRetention() updates

### PR DESCRIPTION
**Pull request by Travis-Owens**
Fixed time conversion in checkRetention(). 
    -Converted to one hour instead of 1 second.
Removed useless comment block in checkRetention()

### CODE REVIEW

**Comment by Travis-Owens** [comment]
Thank you very much for the contribution!

**Comment by Mathisco-01** [comment]
One quick note: in the livebot.sql file, all the items in the discordchannels have a retentionInterval of 0.
So 0*60*60*60 is still 0. Also not clear if retentionInterval is supposed to be in seconds or miliseconds.

**Comment by Travis-Owens** [comment]
That was test data. The retention notification should be set to false. (I also need to delete several unused columns, I will be pushing an updated SQL file today).

Retention Interval should be represent int(x) hours.

I think the python time() object is milliseconds, however, I'm not sure I did the conversion correctly.

**Comment by Travis-Owens** [comment]
Feel free to mess with the formula that converts time() to hours.

**Comment by Mathisco-01** [comment]
Will do!

**Pull request merged**
